name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Capacitor
        run: |
          npm install @capacitor/android
          npm install @capacitor/core @capacitor/cli
          npx cap init mygame com.mygame.app --web-dir=www
          
      - name: Move Files to www Folder
        run: |
          mkdir www
          cp index.html www/
          cp -r js www/js
          cp -r assets www/assets

      - name: Add Android & Copy Files
        run: |
          npx cap copy

      - name: Setup Java & Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
